### ISSUE TITLE
 Runtime does not offer TCPSockets!

### ISSUE THREAD

**Issue by Akash-dvd** [whiteout-io/tcp-socket#17]
Hi ,
I am trying to use this library on browser.
On node the imap client is working fine.
But no luck on browser.  
I am getting Error: Runtime does not offer TCPSockets!
on chrome for tcp-socket package.
I have used the first usage code of tcp-socket on your npm page.
Help me out .

Link
`https://gist.github.com/Akash-dvd/84beb892938e1f2c8eee

**Comment by felixhammerl** [comment]
yes, that's the intended behavior. node has native tcp sockets and native tls, so that's no problem. on a regular browser, you don't have tcp sockets. they are only available in some priviledged environments (e.g. chrome apps, firefox packaged apps, windows apps 8.1+). [if native tcp sockets are not available, we fall back to socket.io tunnelling](https://github.com/whiteout-io/tcp-socket/blob/master/src/tcp-socket.js#L76). seems like you have socket.io support in your app via the `io` global. 

you could make your webserver the socket.io proxy for your application, or ... use platforms that support the native sockets
