### ISSUE TITLE
Chrome legacy socket API obsolete?

### ISSUE THREAD

**Issue by danaki** [whiteout-io/tcp-socket#24]
Getting this error:
```
Error in response to runtime.getPlatformInfo: TypeError: Cannot read property 'create' of undefined
    at TCPSocket._createLegacySocket (chrome-extension://jjhfjlndikmcdkjlkkomnfelhlbkefmc/node_modules/tcp-socket/src/tcp-socket.js:455:26)
    at Object.callback (chrome-extension://jjhfjlndikmcdkjlkkomnfelhlbkefmc/node_modules/tcp-socket/src/tcp-socket.js:442:26)
    at new TCPSocket (chrome-extension://jjhfjlndikmcdkjlkkomnfelhlbkefmc/node_modules/tcp-socket/src/tcp-socket.js:418:28)
    at Function.TCPSocket.open (chrome-extension://jjhfjlndikmcdkjlkkomnfelhlbkefmc/node_modules/tcp-socket/src/tcp-socket.js:898:16)
    at chrome-extension://jjhfjlndikmcdkjlkkomnfelhlbkefmc/bin/main.js:5:31
    at chrome-extension://jjhfjlndikmcdkjlkkomnfelhlbkefmc/bin/main.js:13:4
```

Seems this check in chromeShim() forces obsolete API which is unavailable in recent versions:
```
                if (platformInfo.os.indexOf("cordova") !== -1) {
                    // chrome.sockets.tcp.secure is not functional on cordova
                    // https://github.com/MobileChromeApps/mobile-chrome-apps/issues/269
                    self._useLegacySocket = false;
                    self._useForgeTls = true;
                } else {
                    self._useLegacySocket = true;
                    self._useForgeTls = false;
                }
```
platformInfo.os.indexOf("cordova") for "mac" gives -1 which sets self._useLegacySocket = true in else block.

Chrome Version 47.0.2526.106 (64-bit)

Please fix

**Comment by felixhammerl** [comment]
Well, shit. This API was deprecated since chrome 33, but it was the only one that actually worked. AFAIK, [chrome.sockets.tcp.secure](https://developer.chrome.com/apps/sockets_tcp#method-secure) still has not been fixed. Word on the street is that Google will deprecate Chrome apps sooner or later anyway... Hoped they'd never actually go through with removing it without fixing the other API first.

This means we can remove the legacy socket code branch :+1: , but we also lose native TLS for STARTTLS :-1:

**Comment by felixhammerl** [comment]
Nope, just checked: Still works in M47! Please make sure you use the right permissions in your manifest.json!

Use this:
```
    "permissions": [{
        "socket": ["tcp-connect"]
    }],
```

Instead of this:
```
    "sockets": {
        "tcp": {
            "connect": ""
        }
    },
```

**Comment by Venryx** [comment]
It appears the "socket" permission as shown in the previous post now only works for apps, instead of extensions.

I get this error when attempting to add it to an extension I'm building: https://i.imgur.com/S6MeYRc.png

It's a shame as it (would have been) the only way to use UDP sockets in extensions. Since apps are being phased out, it means we have no way to use UDP sockets without having users download a native app that connects to our extensions. :/
